/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GriffinDEX__factory } from "./GriffinDEX__factory";
export { MockERC20__factory } from "./MockERC20__factory";
